sonar.projectKey=foodiego
sonar.projectName=FoodieGo
sonar.projectVersion=1.0.0

sonar.sources=gateway/src,user-service/src,food-service/src,order-service/src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**

sonar.javascript.lcov.reportPaths=\
  user-service/coverage/lcov.info,\
  food-service/coverage/lcov.info,\
  order-service/coverage/lcov.info

sonar.coverage.exclusions=**/index.js,**/*.test.js

# Quality Gate (tự động chặn CI nếu không đạt)
sonar.qualitygate.wait=true
