BEGIN;

ALTER TABLE payments 
ADD COLUMN IF NOT EXISTS is_refund_requested BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS gateway_sequence BIGINT,
ADD COLUMN IF NOT EXISTS reconciliation_attempts INT NOT NULL DEFAULT 0;

COMMIT;
